project_id = "wyjgkzauhswkeempnawh"

[functions.send-push-notification]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false
